apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-public
  namespace: cattle-system
spec:
  secretName: rancher-public-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - rancher.kung.dk
  usages:
    - server auth
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
