apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
  annotations:
    lbipam.cilium.io/ips: 10.22.50.62
spec:
  type: LoadBalancer
  selector:
    app: blocky
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: api
      port: 4000
      targetPort: 4000
      protocol: TCP
