apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocky
  namespace: blocky
  labels:
    app: blocky
spec:
  selector:
    matchLabels:
      app: blocky
  endpoints:
    - port: api
      path: /metrics
      interval: 30s
