apiVersion: ENC[AES256_GCM,data:3rY=,iv:oRPmxu7cHwXwL60Se/ww29Hh5U52Mw+0E/9f/3xvKkU=,tag:cQGQX+2QeV1fNsjFBOEr5A==,type:str]
kind: ENC[AES256_GCM,data:m4zKfsq64NXS,iv:UGekWynqTM3yQNP/jvUgRaRDkuXSalus21pnoByqZHw=,tag:kZZf6bo51+s3dQEpdn8q2g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tzKey9ZNJoYPR8Y6G2NBAQ==,iv:17DI+kYVfF3Kjzpf3V2RPrXjsHydV+jGOLkDrSZo+60=,tag:mZBEkma6WiPmi/e2iS0iVQ==,type:str]
    namespace: ENC[AES256_GCM,data:UPsWTDkutA==,iv:ftnABHrIYx9cSXRGKbRxdgDDO+jiwWQ9BCGBXOs+jR0=,tag:nUz0S3gWC6QuwHxcP+tSxg==,type:str]
data:
    message: ENC[AES256_GCM,data:HNLzoHNTe7n2QKdlvSiCRfulfhP9DygtfH40XEYtWOBVYCju1LqhgmJvi1PPcofuXNQzQD5LhgmzxNL1/N3nXeUv7zhvhTbjL1C12c5ncSrjlXUe8DJ367T6mQczDUDPEzA=,iv:AIRsuEpMvnUwqfN3yRQMFvhgREhtJA63qYkWYoPgMs4=,tag:hl8abg/j6Z6cCcf1KcqyPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK2dTOG5vSW53VTEzWHpV
            M0lrN1pHeTJwNnRENW9mL1dGNkJiczIvY2hBClVER2VySDd2YW50TXBGZlZiTU1i
            WlFIS2twWmt4cWxmYWVuZk8wYy9YdDQKLS0tIGRCTG9yN0x1OEJuVkJaVFlrK21r
            WTJIK0RXNlpLVnFBRXJMbnBkZ3JVZG8K2haHlxRnRxthIbsZa7PF46FmOl16fgSh
            fRN37iYKZM+SREPnA+lI38WtwwoyDGq3JceDCDv0328Y+yrj0dRs0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1egvy4ykk2n4lr6xj6ydfnw5l6nl8v8cf045dqqql7jl98ge2pc4qqhx6sj
    lastmodified: "2026-09-13T11:28:36Z"
    mac: ENC[AES256_GCM,data:X3lYX09bNVeSBQQSWTaGq43v95awtCwvX+WHlV0+47fS3UIghmOmert82MtswbsAvhnn+Mzjpy+MKflhyJ2uRNKJbNfZAeN+tplgL4Q3MlXtuh4gru+EV+88JEKqOr+9stBn9jYenECxGY7P/bmmnmFv+CaCpO/pUhvsLCBJ4bc=,iv:gardFmsUeHu4TF+pf9/EOOlzddjELYux0NgzGX2KZ8E=,tag:ViflV/EPIpNYHz0RBXAexA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
