apiVersion: ENC[AES256_GCM,data:8jo=,iv:Hf9grpQd7Y6FKB42UBqgNhwkciR15P7vSk1VMtmDdkA=,tag:taM+94USqbD6w8ZgabxFpw==,type:str]
kind: ENC[AES256_GCM,data:W2522yGE,iv:E9O6mU8rWjMMZkp6qHaRAnb7REAawhilu9Abm2NCzRI=,tag:nV4ijHFf9I85EPGgCAzZ5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:a07dhYsXvUXWrZTwl0Pl6w==,iv:z4VbNosB5L8XXN6hbjRjMy/W/QD6zz+9KOI0f+yxHb0=,tag:QnGLl3Kwe7mdeY9YXh0kOg==,type:str]
    namespace: ENC[AES256_GCM,data:5PB0TebPY7x8YIA=,iv:KuMxSC+ZFCK1s5aadBydVUp20x5eWpgy7g2xJBioRxs=,tag:e7IX63LtlcVywNQz/8tN8Q==,type:str]
type: ENC[AES256_GCM,data:uRiQONq5,iv:B/YuWWNQ22a4DfyG4qstPXCWFjQdBnh81wj+a8wBk3w=,tag:dHaSiGelL+ipF2N3OhAwTA==,type:str]
stringData:
    identity: ENC[AES256_GCM,data:OEPO0CKzdwy3EVIWVsetNbSLWD7KK4rAzFFEeUzs9/2cgrLhNElg0DkviXfJTWjLMY/XnlJKzBdWBAwFAE5VKq/pnFGG8w+TBNzPy7I6spDgzKI3OoLj1IOV01i6rb87mV4oTe9GBlXZJfTintAOFEPDRxEjRV299z4Gg5AQviiAT/Iu9zsHxjzI6z/EAP+eb7ZcloXONZzmMUfSCMNZYFgBxZNpcIEjxAEYjXQX1XwYPhkVeEOGLOJXi9+cTQBOuYjjsV59Fk8a6RpfB0/2JfVgv5dRaY1UNEJDL06pv8AGb8Ayf1nuweplIZVAOXYqkUKqcbCmX3IgY0sDoKm2dpjJDOURdBVE2dHYwsFIALhDUOBoUtupi7VCdJl6SzXcPU+COQrbF8c4jzbn1htqBEt4Ki/LbcH28kP56nR4a+54cjNPWE8ykRjS8qnlJM0r2t3rpb7ZtPLGlOV/uDihvNjvAoD3wtjoDdBv2vzhntNKvXbdZxpi0xgkVvF9PZ4YGHsmZ227aaYRl7e8PZ1x47fef257XrpwHmet,iv:R/J/hScnQAIl3BH5IIUymdjO6kk30XtQRUyGHUW6AgY=,tag:SPnEZ5kvwsJ27ly/f4nCLA==,type:str]
    identity.pub: ENC[AES256_GCM,data:hLbnU5MYwY85jkMdXcFUhr4B5DW3gOz/lei8yJyn51D6PR1bq0hJi8G7DIOB0BeWVEWyZddZ4ke25+iVa9MIneYEBWKNVHkZbhcJZ/MKg1bJJL68aSUQDyoFe68zNTQdXnWrRTcX,iv:Zl13d9XhxLb6vbbRkkTwvxjypAxeFUjBDHWM4sPlKh8=,tag:J08o/XCAGb+wUCwBiFthZw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ggLZXSYg27K/bx5geOrWEWIfygP5VjUHbUI67mUcqvNmNiP9eB23koekLyBSPLsxxxKnQczdtp8FFzswNx8wsFgePbFvsqr1AXmuIJkxK61H9156+EO15avzzxzT6JAZGFTTwWQiSXWyDsr+J7Cz89ENeKMG9OmN8oC1RN/iPM0OQI2jSfq1R5bvWgKYhasJ1M+TX/tnn/juJWHVeVei2lRjNk02Y8vGuxzH,iv:8Tm2tNhhmCq5so9w8rletkHOw+T+BGaynIZiGbKux+Y=,tag:LrY/mMQUMoJxWkchclN99w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTGZMWVJkUDBoSHhEZHdL
            Qktmb1djTXZxOGh0ZUdFcEZRZFdsQ3RNMVJvCkZ1SzRlT0lUUlVrdHU4VGhDZFZC
            cUNXU3h1MDZET2N2RXdIUGdFdVFRWDgKLS0tIG93aFcrU1lNZnBDMHdOay9uUGw0
            aXh5Q0VubHc3cWt0b3VvS1kvWlJkYXcK4zNv12XUlwAEQ1qrVuJp6UIrbwu/6tF4
            aJUfLnL/P0ds8XB39cUmorQ1UlYBxPJ6m4Zu1n8Dn9qwcAbzxke3jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1egvy4ykk2n4lr6xj6ydfnw5l6nl8v8cf045dqqql7jl98ge2pc4qqhx6sj
    lastmodified: "2026-09-13T11:37:22Z"
    mac: ENC[AES256_GCM,data:sLDOhl1XJURI/CC0/tbyM8fnpcdW2lkYaGe9AiGFei3JmEITJMrZ2XAghYs16WL5iDllRuq21s8C+TzsMxjIRi1luwMoPq0oOQytoevZgiwc6gxSv16sjVj1xQ2el3H6Wya7tPx3sRTyNR6JtWWRgNm38nCRDwWO/sxc1NsYpEA=,iv:QFckuZewzZVD4gjW7ZtJJ8zFLE98WWROYOms2Lo8h5o=,tag:hgRO3SfaghQJOq1G3BxxBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
