apiVersion: ENC[AES256_GCM,data:toc=,iv:GNvsZV2bx+SAgSOqh7fePk96Jjcwokz7zb4dmB+2FLY=,tag:iEA0AOegtHn9+tM7rzPKxw==,type:str]
kind: ENC[AES256_GCM,data:itGeZ9JJ,iv:ZXvvO3r7lf5qnvZO4iWA/+JrKg1hM44C7PQafvZPTYs=,tag:ZZfhp+EKfZfY7tNE4GTEqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MHq1Uczg,iv:qrE82fsSZqwbXcNs9AnISo/rN9WPNH5dip3uWCLDFp8=,tag:5n3X66Zd6RilliopRs2c0w==,type:str]
    namespace: ENC[AES256_GCM,data:T3Lp,iv:6CpuIRComowTd/E8qSG314gil3UXSkWeHy4BpdDIEK8=,tag:7vchExUiLBdgP5e4KNqC4Q==,type:str]
type: ENC[AES256_GCM,data:ZeWALArS,iv:+VIsM42QVWb1ynpym3non3tWpD13phIm40iVF1zU3Iw=,tag:RNerWaMaXh6D2sptL+xQ7w==,type:str]
stringData:
    root-password: ENC[AES256_GCM,data:+hdtjPhKqoQOYyeKEX4kGW/pivrvzsbElEu7APCxuWM=,iv:I88FBKtxGerPDQMbeIUIC48HmKBqbpKrqN6l8g7KBV8=,tag:hFE1++vMSMCxRDKpBhCXMg==,type:str]
    wp-config-extra: ENC[AES256_GCM,data:Y6caXhGr9MU7Gmrrtlj78+eXR4ZUYJJcbDeqxV9U5Tzk81sQG4LgkXvEXCUlga8rShe35wfBs72K3ymIn4BEIx8XcDYgzKTqtb6UnKzUnMerHfOzRjwRbwpMvvzL4g0Y+HbIfYCGfxoD/qWonPq9RfDQGDFivN+XI9R+IkNGZ/k4u2UFBGeYN4vN3Y/2asLXOZE3L/Ed8bTuYkiTWIBtbIRVlS7ba/pw0p3YjZmHau6jlpviFMzEHOumZefw3wwDhtwCzjWQjy57lRB8l57mus6+TAvudSXWl1DOq/LeO/+pGcTTIKko0uK+f/CoMXa2bH6ACbZpDq5U6VKzzq0xeOnMPSxV2lSCo/nUY8u1X8hG4v+tELzidm85iNPvsp0w6FvqkwQzt2nlIPH7TqwY73yRd+Xx0kE6mmJWwYKyrabajiZQNJI55HPDuOCXkPzQySfSdKRR7lS0gnevLZpvqRYTxPkD4/zMdqaLRSW2TBoM5FCcu1GPHh8bzEatbKA8GR9Z0t9AtosYOj4NOtyvv0Qjx7hZwsm97asYifg4vjmSJHH+uIUM5phOkGM=,iv:tKGC+hTkeEdhfUm/bLO0waSPk2MiyRYBMfQrxFHtFD4=,tag:ESBF6m2bdf1oPM0kwIOifQ==,type:str]
    wp-password: ENC[AES256_GCM,data:d61JTw+MuL/uGdsDZ2bXSFB4Hmzdm36oWx7YC1xBRPg=,iv:ez4H8FWeH4OLuWLzRxVjnLDn9GEREu5sZ6apfDWeeIk=,tag:RGMdJZsJtsnTVUi2rXYtCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSlI0aVdlY2FwdjMxSkFZ
            V2pYYXhTY2NLYmlBYm56UVFRSFNXM0NVMDFFCjZMVXowZ0Q0cDRZQzY1K0VqSTM2
            YTFqOXlUNVpkTytIckpZTDVQZXBCVUkKLS0tIGhxMXRYTFArRGlWYWRGSlFjbWpa
            STVFeEZ3L3ozY21heXlwMnlNdExrVzAK0UeDbjsv8Ib5UJMtOfAJBfDcjAld2psq
            9DUBrJnzQPaLUSAipi8OL+aKHH9NK35GvWCuL2i9p5EieA1iqS8c1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1egvy4ykk2n4lr6xj6ydfnw5l6nl8v8cf045dqqql7jl98ge2pc4qqhx6sj
    lastmodified: "2026-10-02T15:27:27Z"
    mac: ENC[AES256_GCM,data:Ooiuhjfc6HC2ioVAO6PDc71v4N5OzTD8l2FChNReYYBre0dVkae+5e7r4fy/JGHGWwfBGLnvvbfkWPEOkOEWm8B/5BnpbAlr6lt/kQBYgSKiucFfqNolq/MVhqRbANsuwbuYn77gdSFprK1ZOuyOkkn6fsg/CZ26zQeVBItSHE0=,iv:mX8mqWyt1tqcgaj1OTPToLhHEdy08cA+IZNmoUkar2g=,tag:6jtrxjjDH9KdAn3/u9ivMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
