apiVersion: ENC[AES256_GCM,data:vp4=,iv:jCkx+HQqiK3kAqqGmRjSAZ56LCwHhRzk70ENGjkbYQo=,tag:Q8wJoz+yT2xVR/Hucs7g6Q==,type:str]
kind: ENC[AES256_GCM,data:0+zFh6Fw,iv:G7jafiKn0UCwEyHmcROzHwWIX4YPHn3u8tTWKJ+kiOw=,tag:BMCGGyKYqJVRap5wqaW+wQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QpnBEOa5aae8jMh8,iv:NQXgiR6N1hJMxb1cSe3cxurP/sVDxbGPeg8fCRbpnxg=,tag:bJ6CfBY1ul3TaPJUbgaXUg==,type:str]
    namespace: ENC[AES256_GCM,data:rSv3pD7qDnT5,iv:8EFK9MhtD9ugLbaZWiNW4CKojVuh4o2XrU+F3vx2uzw=,tag:UXV+QJURu+BD+XPCYIZTSQ==,type:str]
type: ENC[AES256_GCM,data:YTyrCfOr,iv:5AujeV86876DPdu+t5Nvy/xOyVRd3qpq5z6J6AbZ4YI=,tag:E1ADrUIfppuuuDCqJaBx2Q==,type:str]
stringData:
    root-password: ENC[AES256_GCM,data:aD4Dxr9HsozXTjgR,iv:JPO1W3isOh7RVpdXDKNtZpiTqwaXgoJHlmcdh5+lsSI=,tag:6voIe1T3gBcyH5kR3p3qnA==,type:str]
    wp-password: ENC[AES256_GCM,data:w5QEkzhq/TVtPr4v,iv:0wOKCDfgsBEWouUbe3AKyc+KhKz5FrMIHuPLBWFo/rA=,tag:K0VAhOu6sljcsOzSh3RBuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY1g4ZWJNVmhiaXdvNVVB
            RDlvMGhTSUdtVUJHdU9HdlF0L0l2aEhNWm1VClhkck5WL0xIUFVaNzhkYlJCUkFw
            OFo1ek54OCtEQTZDb3lPaDl2SHRkdzQKLS0tIDByaEtUekpxMWVwckNSNG1FRXRH
            QUdBRDJRdEh4azdnd0hJRG10TWNydmsKxDPd4QKsvIcWESEmRqINAXacg9M3vERz
            DYrY13GzUbwzznumRwIp6AGCPjsxGAcCV5mHmh0HfzhrkTYkSvmD6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1egvy4ykk2n4lr6xj6ydfnw5l6nl8v8cf045dqqql7jl98ge2pc4qqhx6sj
    lastmodified: "2026-09-13T11:16:06Z"
    mac: ENC[AES256_GCM,data:lyq8dHPpH9QqXF925DIX9+iuk5841VZlLo4lCQwouSjlUYF6LuySFta/r76yS7UxgUMBggPrNwJfDtKN5JqOl9a3MUtjmMQxXUeyHLBTOugX53fHsWL5dNQyGgjWICU0YaBi9xgqMq+C9NfUcNqN6kJlMQA3yRC7GITm7vHat6M=,iv:wEpC99dw8i6bfaluGQtIX+MkG89kiHQj77tR+oeySbs=,tag:S5MWdP2biTL3/CqCO7TjrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
